name: helfer_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  assets: ^0.0.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.5.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  firebase_storage: ^11.6.7
  image_picker: ^1.0.7
  flutter_auth_provider: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.2


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
  
