// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdNY3DPDTg5bQKb8FDHCtARmtlKT-6lA',
    appId: '1:768561745280:web:44f79d3d9cbce6da63c565',
    messagingSenderId: '768561745280',
    projectId: 'test-app-11383',
    authDomain: 'test-app-11383.firebaseapp.com',
    storageBucket: 'test-app-11383.appspot.com',
    measurementId: 'G-WSTFWYRY8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jNZvH4ONtG5BC7kDBz56Lmf7V5lwgPI',
    appId: '1:768561745280:android:620b4bea8980449363c565',
    messagingSenderId: '768561745280',
    projectId: 'test-app-11383',
    storageBucket: 'test-app-11383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIl3cI3RPe1DTC8Fj3VXmv7JbFHFH4XTE',
    appId: '1:768561745280:ios:b741327909b1bc7a63c565',
    messagingSenderId: '768561745280',
    projectId: 'test-app-11383',
    storageBucket: 'test-app-11383.appspot.com',
    iosBundleId: 'com.example.helferApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIl3cI3RPe1DTC8Fj3VXmv7JbFHFH4XTE',
    appId: '1:768561745280:ios:8c9d420700935e1a63c565',
    messagingSenderId: '768561745280',
    projectId: 'test-app-11383',
    storageBucket: 'test-app-11383.appspot.com',
    iosBundleId: 'com.example.helferApp.RunnerTests',
  );
}
