// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QU7Tm5A1pZvRXIZQcxvvHFLVoeoaVwk',
    appId: '1:589261855054:web:df4ef0ff75a37ba380a61f',
    messagingSenderId: '589261855054',
    projectId: 'helfer-app-a7bc4',
    authDomain: 'helfer-app-a7bc4.firebaseapp.com',
    storageBucket: 'helfer-app-a7bc4.appspot.com',
    measurementId: 'G-VYTBWQR685',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQlegMGzBUg06ouLpcfCjyrQpcp9XHL_w',
    appId: '1:589261855054:android:7c0bb12ea778a42380a61f',
    messagingSenderId: '589261855054',
    projectId: 'helfer-app-a7bc4',
    storageBucket: 'helfer-app-a7bc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsvGHwODJqCU5no0FOspYsYi2b09W6SkU',
    appId: '1:589261855054:ios:1e736c209991413380a61f',
    messagingSenderId: '589261855054',
    projectId: 'helfer-app-a7bc4',
    storageBucket: 'helfer-app-a7bc4.appspot.com',
    iosBundleId: 'com.example.helferApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsvGHwODJqCU5no0FOspYsYi2b09W6SkU',
    appId: '1:589261855054:ios:94a4b05de36d08d580a61f',
    messagingSenderId: '589261855054',
    projectId: 'helfer-app-a7bc4',
    storageBucket: 'helfer-app-a7bc4.appspot.com',
    iosBundleId: 'com.example.helferApp.RunnerTests',
  );
}
